### ISSUE TITLE
Incorrect TXT Value

### ISSUE THREAD

**Issue by williamcolbert** [caddy-dns/digitalocean#3]
Hello,

I was trying to use this to get a wildcard certification, and it kept failing on me.  When I dug deeper I noticed it was because the host value on the TXT record in digital ocean was incorrect it had duplicated the domain part.  I just duplicated the record without the double host and it got the certification just fine. If someone can point me in the right direction I can create a pull request for the fix. 

**DNS Record that was added by the plugin:**
```
Record Type: TXT	
Host: _acme-challenge.domain.com.domain.com
Value: [Removed]
TTL: 1800
```

**Config**
```
domain.com {
    root * /var/www/public
    php_fastcgi 127.0.0.1:9000

    encode gzip
    file_server
    tls {
        dns digitalocean [API Token]
    }
}
```

**Comment by williamcolbert** [comment]
Looks like tied to this issue here. 
https://github.com/libdns/digitalocean/pull/3

**Comment by IronSinew** [comment]
Can confirm. Ran into this today as well, even without a wildcard attempt. I had to remove the digitalocean resolver reference from my caddyfile to get a cert to generate, which is leaving me without a wildcard at the moment. The txt hostnames present in the dns records are akin to: `_acme-challenge.domain.tld.domain.tld` -- which is obviously incorrect
